# Site
repository: hongkyun-bae/hongkyunbae.github.io
favicon: images/favicon.ico

# Personal info
name: Hong-Kyun Bae
title: Assistant Professor
#email: hjkim@theory.snu.ac.kr
email: hongkyun@hanyang.ac.kr
website: hongkyunbae.github.io
#lab: sites.google.com/view/hyudatalab 

# Social links
#twitter_username: facespics
github_username:  hongkyun-bae
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: hong-kyun-bae
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
googlescholar_username: pmX6O10AAAAJ&hl=en
cv_username: hkbaeCV

# About Section
# about_title: About Me
about_profile_image: images/hkbae.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Hong-Kyun Bae. I serve as a postdoctoral researcher in the Department of Computer Science at Hanyang University. I earned my B.S. in Computer Science and Engineering from Inha University. In 2023, I had the opportunity to be a visiting scholar at Pennsylvania State University for three months. I completed my Ph.D. in Computer Science from Hanyang University in 2024 under the guidance of Professor Sang-Wook Kim.
  My research focuses on <mark>Recommender Systems</mark>, <mark>Data Mining</mark>, and <mark>Artificial Intelligence</mark>. 
 
# Education Section
educaton_title: Education

# Experience Section
experience_title: Work Experience

# Publications Section
publications_title: Selected Publications

# Projects Section
#projects_title: Projects

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: hongkyun-bae/hongkyunbae.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# Show future posts
future: true
# Specify my timezone
timezone: TIMEZONE

theme: jekyll-theme-minimal
